<?php

    $refundStatus = json_encode($block->getRefundStatus()->getData());
    $orderRefund = json_encode($block->getOrderRefund());
    $orders = json_encode($block->getOrderCollectionByCutomerId());
?>

<?php if ($block->getConfigEnableModule()) { ?>
    <div id="starbucksb2b-refund-modal" style="display: none;">
        <form action="" class="form refund" id="starbucksb2b-refund-form" method="post"
              data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}' enctype="multipart/form-data">
            <fieldset class="fieldset">
                <div class="control">
                    <?php $title = $block->getTitle(); ?>
                    <p><?php echo $title ? $title : __("We are sorry to know that you want a refund. Please let us know what's wrong"); ?></p>
                </div>
                <div class="control">
                    <input type="hidden" name="starbucksb2b-refund-order-id" value="" class="starbucksb2b-refund-oder-id">
                    <?php $formKey = $block->getFormKey()?>
                    <input type="hidden" name="form_key" value="<?= $block->escapeHtml($formKey) ?>" class="form_key">
                </div>
                <?php if ($block->getConfigEnableDropdown()) : ?>
                    <div class="field required">
                        <?php $dropdownTitle = $block->getDropdownTitle(); ?>
                        <label class="label" for="label"><span><?php echo $dropdownTitle ? $dropdownTitle : __('Reason for refund'); ?></span></label>
                        <div class="control">
                            <label>
                                <select name="starbucksb2b-option">
                                    <?php $a = $block->getLabel(); ?>
                                        <?php foreach ($a as $value) { ?>
                                            <option><?php echo $value->getData('request_label'); ?></option>
                                    <?php } ?>
                                </select>
                            </label>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($block->getConfigEnableOption()) : ?>
                    <div class="field required">
                        <?php $optionTitle = $block->getOptionTitle(); ?>
                        <label class="label" for="label"><span><?php echo $optionTitle ? $optionTitle : __('Product is opened'); ?></span></label>
                        <div class="control">
                            <label>
                                <input type="radio" name="starbucksb2b-radio" value="1" required="required">
                            </label><span><?= $block->escapeHtml(__('Yes')) ?></span>
                            <label>
                                <input type="radio" name="starbucksb2b-radio" value="0">
                            </label><span><?= $block->escapeHtml(__('No')) ?></span>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field required">
                    <?php $detailTitle = $block->getDetailTitle(); ?>
                    <label class="label" for="label"><span><?php echo $detailTitle ? $detailTitle : __('Faulty or other detail'); ?></span></label>
                    <div class="control">
                        <label>
                            <textarea class="starbucksb2b-refund-reason input-text" name="starbucksb2b-refund-reason" data-validate="{required:true}"></textarea>
                        </label>
                    </div>
                </div>
				
				   <div class="field ">
                    <label class="label" for="label"><span><?php echo  __('Upload file'); ?></span></label>
                    <div class="control">
                        <label>						
                   <input name="starbucksb2b-image" id="starbucksb2b-image" class="admin__control-file" title="Image" value="" class="starbucksb2b-image input-file" type="file">

                        </label>
                    </div>
                </div>
<input class="btn btn-success starbucksb2b-popup-button" type="submit" value="Upload">

            </fieldset>
        </form>
    </div>
    <div id="message"></div>
    <?php $poptupTitle = $block->getPopupModuleTitle();?>
    <script type="text/x-magento-init">
        {
            "*":
                {
                    "Starbucksb2b_RequestCredit/js/get-oder": {
                        "orderRefund" : <?php echo $orderRefund; ?>,
                        "starbucksb2bUrl" : "<?php echo $block->getBaseUrl(); ?>",
                        "starbucksb2bPopupTitle" : "<?php echo $poptupTitle ? $poptupTitle : __('Request Credit');?>",
                        "dataOrder" : <?php echo $refundStatus; ?>,
                        "orders": <?php echo $orders ?>
                    }
                }

        }
    </script>
<?php   } ?>